spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - StripPrefix=1 # This filter strips the first segment in the path

server:
  port: 9191

management:
  tracing:
    sampling:
      probability: 1.0 # Ensure tracing spans are always sent
  metrics:
    export:
      simple:
        enabled: true # Default metrics
      prometheus:
        enabled: false # Enable Prometheus if needed
micrometer:
  tracing:
    export:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans # Pointing to Zipkin's HTTP API


logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
