spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - StripPrefix=1 # This filter strips the first segment in the path
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9192

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
